@PatientService_HostAddress = https://localhost:7022
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZjIzMGEyZC02NGM2LTRkMjYtOWUxNC0wZjE0MzgyMjcwYTQiLCJlbWFpbCI6ImhlaW5AdGVzdC5jb20iLCJyb2xlIjoiVXNlciIsIm5iZiI6MTc2NDMxMDQ2MiwiZXhwIjoxNzY0MzE0MDYyLCJpYXQiOjE3NjQzMTA0NjIsImlzcyI6IllvdXJJc3N1ZXIiLCJhdWQiOiJZb3VyQXVkaWVuY2UifQ.h4qPR95XXVMGpP-YvxwzvqKj0gtIvZfStBEa4AzZeYI

GET {{PatientService_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{PatientService_HostAddress}}/api/patient/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "dateOfBirth": "1990-01-01",
  "medicareNumber": "1234567890",
  "medicareReference": 1
}